include: package:pedantic_mono/analysis_options.yaml
analyzer:
  errors:
    import_of_legacy_library_into_null_safe: false
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.chopper.dart
    - lib/l10n/*.dart
linter:
  rules:
    sort_pub_dependencies: false
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false